version: "3"

services:
  symfony-basic-setup:
    container_name: "symfony-basic-latest"
    env_file:
      - .env
    build: 
      context: ./docker
      dockerfile: symfony.dockerfile
    environment:
       - PORT=${PORT}
    volumes:
         - "./app/:/var/www/html/"
    ports:
        - "${PORT}:${PORT}"
