version: "3"

services:
  symfony-basic-latest:
    container_name: "symfony-basic-latest"
    env_file:
      - .env
    build: 
      context: .
      dockerfile: symfony.dockerfile
    environment:
       - PORT=${PORT}
       - TIMEZONE=${TIMEZONE}
       - PHP_VERSION=${PHP_VERSION}
    volumes:
         - "./app/:/var/www/html/"
    ports:
        - "${PORT}:${PORT}"
